x=int(input("enter Regular pay value : \n"))
print("\n \n")

print("EARNINGS",end="\n\t")
print("Dearness_Pay:"+str(int(x/5.43463287)),end="\n\t")
print("HRA:"+str(int(x/6.25)),end="\n\t")
print("Lunch Allowance:"+str(int(x/100)),end="\n\t")
print("Conveyance/Transport allo:"+str(int(x/28.5662563)),end="\n\t")
print("Education Allowance:"+str(int(x/50)),end="\n\t")
print("Periodicals Allowance:"+str(int(x/100)),end="\n\t")
print("Telephone & Internet:"+str(int(x/66.63)),end="\n\t")
print("Phone Call Refund:"+str(int(x/438.33)),end="\n\t")
print("Special Comp Allow:"+str(int(x/26.458)),end="\n\t")
print("Performance Related Pay:"+str(int(x/17.533)),end="\n\t")
print("Washing Allowance:"+str(int(x/100)),end="\n\n")

print("DEDUCTIONS",end="\n\t")
print("PF Regular:"+str(int(x/7.038)),end="\n\t")
print("PF Extra:"+str(int(x/18.07)),end="\n\t")
print("ProfTax:200",end="\n\t")
print("Canteen Recovery:"+str(int(x/1643.75)),end="\n\t")
print("Lunch Recovery officers:"+str(int(x/737.3831)),end="\n\t")
print("LIC Premium:2480",end="\n\t")
print("BEML Insurance:"+str(int(x/32.61678)),end="\n")

print("FORM 16 Summary",end="\n\t")
print("Gross Salary:"+str(int(x+1277227)),end="\n\t")
print("Incm under Hd Salary:"+str(int(1195234+(x*0.62))),end="\n\t")
print("Gross Tot Income:"+str(int(1023750+(x*1.36935361))))